### ISSUE TITLE
Fatal error: Uncaught exception 'Twig_Error_Syntax'

### ISSUE THREAD

**Issue by amklose** [pattern-lab/edition-php-drupal-standard#21]
I installed a fresh version of this project following the instructions in README.md. When I try to run the command `php core/console --generate`, I get the following error and stack trace. Did I do something wrong?
```
Fatal error: Uncaught exception 'Twig_Error_Syntax' with message 'Unexpected character "#" in "{{# adminView }}
  <h2 class="element-invisible">Primary tasks</h2>
  <ul class="nav nav--primary-local-tasks">
    <li class="nav__item is-active"><a class="nav__link active" href="{{ url }}">View<span class="element-invisible">(active tab)</span></a></li>
    <li class="nav__item"><a class="nav__link" href="{{ url }}">Edit</a></li>
    <li class="nav__item"><a class="nav__link" href="{{ url }}">Manage display</a></li>
  </ul>
{{/ adminView }}
" at line 1.' in <drupal installation path>/themes/patternlab/vendor/twig/twig/lib/Twig/Lexer.php:284
Stack trace:
#0 <drupal installation path>/themes/patternlab/vendor/twig/twig/lib/Twig/Lexer.php(216): Twig_Lexer->lexExpression()
#1 <drupal installation path>/themes/patternlab/vendor/twig/twig/lib/Twig/Lexer.php(115): Twig_Lexer->lexVar()
#2 <drupal installation path>/themes/patternlab/vendor/twig/twig/lib/Twig/Environment.php(581): Twig_Lexe in <drupal installation path>/themes/patternlab/vendor/twig/twig/lib/Twig/Lexer.php on line 284
```

**Comment by aleksip** [comment]
Looks like you installed [Twig Gesso StarterKit for Drupal](https://github.com/forumone/starterkit-twig-drupal-gesso)?  This seems to be a problem with that StarterKit, so you might want to open an issue there.

Or if you are just checking out Standard Edition for Drupal, you might want to try another suggested StarterKit.

**Comment by coreylafferty** [comment]
Thanks for catching this.  There was some left over mustache syntax in one of the Gesso StarterKit patterns from our conversion to twig.  It's been fixed now.
